

services:
  cybertruck-db:
    image: postgres:alpine3.19
    container_name: cybertruck-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cybertruck
    volumes:
      - cybertruck:/var/lib/postgresql/data

  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    restart: always
    ports:
      - 1880:1880
    depends_on:
      - cybertruck-db
    volumes:
      - nodered_data:/data

volumes:
  cybertruck:
  nodered_data:
