/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_VEHICLE_PB_H_INCLUDED
#define PB_VEHICLE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _VehicleCommand {
    int32_t vehicle_id;
    int32_t agent_id;
    char actuator[11];
    char cmd[21];
    int32_t value;
} VehicleCommand;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define VehicleCommand_init_default              {0, 0, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define VehicleCommand_init_zero                 {0, 0, {{NULL}, NULL}, {{NULL}, NULL}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define VehicleCommand_vehicle_id_tag            1
#define VehicleCommand_agent_id_tag              2
#define VehicleCommand_actuator_tag              3
#define VehicleCommand_cmd_tag                   4
#define VehicleCommand_value_tag                 5

/* Struct field encoding specification for nanopb */
#define VehicleCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    vehicle_id,        1) \
X(a, STATIC,   SINGULAR, INT32,    agent_id,          2) \
X(a, CALLBACK, SINGULAR, STRING,   actuator,          3) \
X(a, CALLBACK, SINGULAR, STRING,   cmd,               4) \
X(a, STATIC,   SINGULAR, INT32,    value,             5)
#define VehicleCommand_CALLBACK pb_default_field_callback
#define VehicleCommand_DEFAULT NULL

extern const pb_msgdesc_t VehicleCommand_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define VehicleCommand_fields &VehicleCommand_msg

/* Maximum encoded size of messages (where known) */
/* VehicleCommand_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
